version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: math-platform-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mathplatform
    ports:
      - "5432:5432"
    volumes:
      - postgres_:/var/lib/postgresql/data

volumes:
  postgres_
